<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>

  <PropertyGroup Label="General">
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <UsingAssemblyInfoTemplate>true</UsingAssemblyInfoTemplate>
    <SkipServerCertificateValidation>true</SkipServerCertificateValidation>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Label="Framework" Condition="'$(TargetFramework)' == '' OR '$(TargetFrameworks)' == ''">
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Label="Analysis">
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

</Project>
