<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>sdmonitor-simulator</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SDMonitor\SDMonitor.csproj" />
  </ItemGroup>

</Project>
