<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>sdmonitor</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.6.4" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SDMonitor.Tests" />
    <InternalsVisibleTo Include="sdmonitor-simulator" />
  </ItemGroup>

  <ItemGroup>
    <None Update="dashboard-tiles.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
